/**
 * The English interface, one file (founder s207).
 *
 * The app is written German-first, so **the German string is the key** and this
 * map holds its English. A key that is missing renders the German, which is
 * what the app did before this file existed, so coverage grows surface by
 * surface without ever leaving a blank or a crash behind. The rule that picks
 * between the two lives in `src/lib/uiLang.ts`.
 *
 * ## What belongs in here
 *
 * CHROME only: labels, buttons, headings, helper lines, toasts, empty states.
 *
 * ## What must NEVER be added
 *
 * The learning material. A vocabulary word, its example sentence, a Redemittel
 * phrase, a grammar drill, an exam text, a writing brief, anything from
 * `src/data/*` is the thing the learner came to read in German, and translating
 * it would delete the exercise. The existing EN glosses (hold-to-peek, the
 * Gloss component) stay the only place a learner is handed an English meaning,
 * because there it is a deliberate teaching move.
 *
 * A `Key#context` entry wins over the bare `Key` for a call site that passes
 * that context, for the rare German word that needs two different English ones.
 */
export const UI_EN: Record<string, string> = {
  /* ---------------------------------------------------------------- nav --- */
  Bibliothek: "Library",
  "Prüfung": "Exam",
  Fortschritt: "Progress",
  Praktisch: "Practice",
  Einstellungen: "Settings",
  Kontrollzentrum: "Control center",
  Suche: "Search",
  "Zur Startseite": "To the start page",
  "Deutsch im Beruf · B2": "German for work · B2",

  /* -------------------------------------------------------------- shell --- */
  "Guten Morgen": "Good morning",
  Hallo: "Hello",
  "Guten Abend": "Good evening",
  "Prüfung verlassen": "Leave the exam",
  "Zurück": "Back",
  Verlassen: "Leave",
  Tag: "day",
  Tage: "days",
  Serie: "Streak",
  "Schreibtraining wird fortgesetzt …": "Resuming your writing practice …",

  /* ------------------------------------------------------- account menu --- */
  Konto: "Account",
  Gast: "Guest",
  "Nicht angemeldet": "Not signed in",
  Synchronisiert: "Synced",
  "Nur lokal": "This device only",
  Design: "Appearance",
  Hell: "Light",
  Dunkel: "Dark",
  System: "System",
  "Konto erstellen": "Create account",
  Anmelden: "Sign in",
  Abmelden: "Sign out",
  "Du wurdest abgemeldet.": "You have been signed out.",
  "Konto & Cloud-Sync": "Account & cloud sync",
  "Sync pausiert": "Sync paused",
  "Dein Fortschritt wird gerade nur auf diesem Gerät gespeichert. Er geht nicht verloren, erreicht aber die Cloud noch nicht.":
    "Your progress is currently saved on this device only. Nothing is lost, but it has not reached the cloud yet.",
  "Erneut versuchen": "Try again",
  angemeldet: "signed in",
  "Du bist als Gast unterwegs – dein Fortschritt liegt in der Cloud. Erstelle ein Konto, um dich auf weiteren Geräten anzumelden.":
    "You are here as a guest, and your progress is in the cloud. Create an account to sign in on other devices.",
  "Erstelle ein Konto, um deinen Fortschritt geräteübergreifend zu sichern. Kein Konto nötig – du kannst auch als Gast weitermachen.":
    "Create an account to keep your progress across devices. No account needed, you can also carry on as a guest.",
  "Als Gast fortfahren": "Continue as guest",
  "Sichere deinen Fortschritt": "Save your progress",
  "Melde dich an, um auf allen Geräten weiterzulernen. Kein Passwort nötig.":
    "Sign in to keep learning on all your devices. No password needed.",
  "Hinweis schließen": "Dismiss",

  /* --------------------------------------------------------- onboarding --- */
  "Wofür lernst du Deutsch?": "What are you learning German for?",
  Beruf: "Work",
  "Job & Büro": "Job & office",
  Alltag: "Everyday life",
  "Behörde, Arzt, Bank": "Public offices, doctor, bank",
  "telc / Goethe B2": "telc / Goethe B2",
  Beides: "Both",
  "Beruf & Alltag": "Work & everyday life",
  "Dein Niveau": "Your level",
  "Los geht's": "Let's go",
  "In unter einer Minute in deiner Bibliothek": "In your library in under a minute",
  "Ich stimme den": "I accept the",
  AGB: "Terms",
  "und der": "and the",
  "Datenschutzerklärung": "Privacy Policy",
  "zu.": ".",

  /* ---------------------------------------------------------- Bibliothek --- */
  "Wörter": "Words",
  Kollokationen: "Collocations",
  Redemittel: "Phrases",
  Grammatik: "Grammar",
  Kontext: "Context",
  "Kontext entfernen": "Clear context",


  /* ------------------------------------------------- filters & taxonomy --- */
  Filter: "Filters",
  "Filter zurücksetzen": "Reset filters",
  "Filter schließen": "Close filters",
  "Zurücksetzen": "Reset",
  "Schließen": "Close",
  Ansicht: "View",
  Anheften: "Pin",
  anheften: "pin",
  "lösen": "unpin",
  "Angeheftet: bleibt beim Einklappen sichtbar": "Pinned: stays visible when collapsed",
  "Mehr anzeigen": "Show more",
  "Weniger anzeigen": "Show less",
  entfernen: "remove",
  Lebensbereich: "Life area",
  Berufsleben: "Working life",
  Thema: "Topic",
  Themen: "topics",
  Unterthema: "Sub-topic",
  Unterthemen: "sub-topics",
  Branche: "Sector",
  "Alle Themen": "All topics",
  "Alle Branchen": "All sectors",
  "Alle Kategorien": "All categories",
  "Alle Gruppen": "All groups",
  "Gesamtes Thema": "Whole topic",
  "Für dieses Thema gibt es nichts nach Branche. Du übst hier alles.":
    "There is nothing sector-specific for this topic. You practise everything here.",
  Kategorie: "Category",
  Gruppe: "Group",
  Textsorte: "Text type",
  Niveau: "Level",
  Stufe: "Level",
  "Stufe (CEFR)": "Level (CEFR)",
  "Stufe: bis": "Level: up to",
  Mehrfachauswahl: "Multiple choice",
  Wortart: "Word class",
  "Häufigkeit": "Frequency",
  Register: "Register",
  Lernstand: "Learning state",
  Nomen: "Noun",
  Verb: "Verb",
  Adjektiv: "Adjective",
  Adverb: "Adverb",
  Phrase: "Phrase",
  Konnektor: "Connector",
  Kernwortschatz: "Core vocabulary",
  "häufig": "common",
  Fachsprache: "Specialist",
  neutral: "neutral",
  formell: "formal",
  "Medizin & Pflege": "Healthcare & nursing",
  Handwerk: "Trades",
  "IT & Software": "IT & software",
  Handel: "Retail",
  Gastronomie: "Hospitality",
  Ingenieurwesen: "Engineering",
  "Bau & Architektur": "Construction & architecture",
  Produktion: "Production",
  "Transport & Logistik": "Transport & logistics",
  "Beauty & Kosmetik": "Beauty & cosmetics",
  "Sport & Fitness": "Sport & fitness",
  "Chemie & Kunststoff": "Chemicals & plastics",
  "Pharma & Medizintechnik": "Pharma & medical technology",
  Reinigung: "Cleaning",
  Sicherheitsdienste: "Security services",

  /* -------------------------------------------------------- Wörter tab --- */
  Tabelle: "Table",
  Graph: "Graph",
  Karten: "Cards",
  Liste: "List",
  "Übersicht": "Overview",
  Karteikarten: "Flashcards",
  Quiz: "Quiz",
  "Suchen …": "Search …",
  "Suche nach Wort, Übersetzung …": "Search by word, translation …",
  "Nur gespeicherte Wörter": "Saved words only",
  Gespeichert: "Saved",
  "Wort speichern": "Save word",
  "Noch keine gespeicherten Wörter. Tippe das Lesezeichen an einem Wort.":
    "No saved words yet. Tap the bookmark on a word.",
  Wort: "Word",
  "Wörtern": "words",
  Plural: "Plural",
  Englisch: "English",
  "kein Plural": "no plural",
  "nur Plural": "plural only",
  "Präteritum": "Past tense",
  "mit zu": "with zu",
  Verbunden: "Related",
  Weniger: "Less",
  neu: "new",
  lernen: "learning",
  wiederholen: "review",
  gemeistert: "mastered",
  "Drei Wesen zeigen den Artikel": "Three creatures show the article",
  "Jedes Nomen bekommt sein Wesen neben dem Wort. So siehst du den Artikel auf einen Blick.":
    "Every noun gets its creature next to the word, so you see the article at a glance.",

  /* ------------------------------------------------------------ feedback --- */
  "Feedback geben": "Give feedback",
  Feedback: "Feedback",
  "Diese App wird gerade mit KI entwickelt (Beta). Dein Feedback hilft uns sehr, sie besser zu machen. Was ist dir aufgefallen?":
    "This app is being built with AI (beta). Your feedback really helps us make it better. What did you notice?",
  "Deine Nachricht, Idee oder ein Fehler …": "Your message, idea or a bug …",
  "E-Mail (optional, falls wir dich erreichen dürfen)":
    "Email (optional, in case we may reach you)",
  "Wird gesendet …": "Sending …",
  Senden: "Send",
  "Danke für dein Feedback!": "Thanks for your feedback!",
  "Konnte nicht gesendet werden.": "Could not be sent.",
  "Etwas verbessern?": "Something to improve?",

  /* ----------------------------------------------------------- settings --- */
  Profil: "Profile",
  Name: "Name",
  "Dein Name": "Your name",
  Sprachniveau: "Language level",
  "Tägliches XP-Ziel": "Daily XP goal",
  "50 XP · Entspannt": "50 XP · Relaxed",
  "80 XP · Stetig": "80 XP · Steady",
  "120 XP · Ehrgeizig": "120 XP · Ambitious",
  "200 XP · Intensiv": "200 XP · Intense",
  "Prüfungsdatum": "Exam date",
  Lernen: "Learning",
  Lernmodus: "Learning focus",
  "Worauf dein Tag den Fokus legt: Beruf, Alltag oder beides.":
    "What your day focuses on: work, everyday life or both.",
  "Erst überlegen, dann Optionen": "Think first, then see the options",
  "Bei Auswahlfragen kurz selbst antworten, bevor die Optionen erscheinen. Das stärkt den Abruf.":
    "On multiple-choice questions, answer for yourself before the options appear. It strengthens recall.",
  "Langsame Antworten öfter wiederholen": "Repeat slow answers more often",
  "Wenn du eine Antwort zwar richtig, aber deutlich langsamer als sonst gibst, wird sie früher wieder abgefragt.":
    "When you get an answer right but much slower than usual, it comes back sooner.",
  "Gespeicherte Wörter": "Saved words",
  "Tippe das Lesezeichen an einem Wort, um es öfter zu üben.":
    "Tap the bookmark on a word to practise it more often.",
  Ansehen: "View",
  Darstellung: "Appearance",
  "Reduzierte Animation": "Reduced motion",
  "Weniger Bewegung in der UI": "Less movement in the interface",
  Sprachausgabe: "Speech",
  "Text-zu-Sprache": "Text to speech",
  "Aussprachehilfe für Vokabeln & Dialoge": "Pronunciation help for words & dialogues",
  Sprechgeschwindigkeit: "Speaking rate",
  "Stimme (Deutsch)": "Voice (German)",
  "Stimmen abwechseln": "Alternate voices",
  "Wechselt bei jeder Wiedergabe zwischen den verfügbaren deutschen Stimmen.":
    "Switches between the available German voices on every playback.",
  Spracherkennung: "Speech recognition",
  "Schaltet Sprechblöcke in Sessions frei. Experimentell, nicht auf allen Geräten verfügbar":
    "Unlocks speaking blocks in sessions. Experimental, not available on every device",
  "Deine Daten": "Your data",
  "Lade eine Kopie deiner Daten als JSON herunter: dein Profil, dein Lernfortschritt und (wenn du angemeldet bist) deine gespeicherten Schreib-Auswertungen.":
    "Download a copy of your data as JSON: your profile, your learning progress and (when signed in) your saved writing evaluations.",
  "Daten exportieren": "Export data",
  "Datenexport heruntergeladen.": "Data export downloaded.",
  "Export fehlgeschlagen. Bitte versuche es erneut.": "Export failed. Please try again.",
  Gefahrenzone: "Danger zone",
  "Fortschritt zurücksetzen": "Reset progress",
  "Bist du sicher? Diese Aktion kann nicht rückgängig gemacht werden.":
    "Are you sure? This cannot be undone.",
  Abbrechen: "Cancel",
  "Ja, Fortschritt löschen": "Yes, delete my progress",
  "Fortschritt zurückgesetzt (auch in der Cloud).": "Progress reset (in the cloud too).",
  "Lokal zurückgesetzt. Die Cloud wird synchronisiert, sobald du online bist.":
    "Reset on this device. The cloud syncs as soon as you are online.",
  "Lokaler Fortschritt zurückgesetzt.": "Local progress reset.",
  "Konto löschen": "Delete account",
  "Konto endgültig löschen": "Permanently delete account",
  "Dein Konto wurde gelöscht.": "Your account has been deleted.",
  "Konto konnte nicht gelöscht werden. Bitte versuche es erneut.":
    "The account could not be deleted. Please try again.",
  "Hilfe & Anleitungen": "Help & guides",
  "Quellen & Lizenzen": "Sources & licences",
  Sprache: "Language",
  "Automatisch (nach Niveau)": "Automatic (follows your level)",
  Deutsch: "German",
  "A2 und B1 sehen die Oberfläche auf Englisch, B2 und C1 auf Deutsch. Der Lernstoff ist immer auf Deutsch.":
    "A2 and B1 read the interface in English, B2 and C1 in German. The learning material is always German.",

  /* ------------------------------------- trainers, exam, game, chrome --- */
  "Abschließen": "Finish",
  "Aktivitätskalender": "Activity calendar",
  "Alle Kompetenzen erreicht. Neue Themen schalten neue Quests frei.": "Every skill reached. New topics unlock new quests.",
  "Alle Niveaus": "All levels",
  "Als Nächstes": "Up next",
  "Antwort korrigieren": "Correct your answer",
  "Auf die erkannte Form zurücksetzen": "Reset to the detected form",
  Aufgabe: "Task",
  "Aufgabe vergrößern": "Enlarge the task",
  "Aufgabe wählen": "Choose a task",
  "Auswahl schließen": "Close the picker",
  "Auswahl zurücksetzen": "Reset selection",
  "Auswertung löschen": "Delete evaluation",
  Bestanden: "Passed",
  Bester: "Best",
  "Bestätigt": "Confirmed",
  "Bestätigungs-Links laufen ab und lassen sich nur einmal öffnen. Melde dich an, dann": "Confirmation links expire and open only once. Sign in, then",
  "Bewertet wird:": "Marked on:",
  "Blass: dein erster Versuch · Kräftig: dein Fortschritt": "Pale: your first attempt · Solid: your progress",
  "Das Transkript wurde inzwischen gelöscht.": "The transcript has since been deleted.",
  "Das musst du schaffen": "What you need to manage",
  "Dein Fortschritt wird nicht gespeichert. Möchtest du wirklich zurück?": "Your progress will not be saved. Do you really want to go back?",
  "Dein Gespräch ist gespeichert und steht in deinem Verlauf.": "Your conversation is saved and sits in your history.",
  "Dein Satz": "Your sentence",
  "Dein Satz wird von einer KI (Anthropic, Google oder OpenAI) geprüft und umgeformt. Die": "Your sentence is checked and reshaped by an AI (Anthropic, Google or OpenAI). The",
  "Dein Stärkeprofil": "Your strength profile",
  "Dein Text": "Your text",
  "Dein Text wird zur Auswertung an eine KI (Anthropic, Google oder OpenAI) gesendet. Die": "Your text is sent to an AI (Anthropic, Google or OpenAI) for evaluation. The",
  "Dein Text wird zur Auswertung an eine KI gesendet.": "Your text is sent to an AI for evaluation.",
  "Deine Antwort (optional) …": "Your answer (optional) …",
  "Deine Antwort auf Deutsch …": "Your answer in German …",
  "Deine Entwicklung": "Your progress over time",
  "Deine Notizen": "Your notes",
  "Deine Rückmeldung wird erstellt …": "Your feedback is being written …",
  "Deine Sammlung ist noch leer. Übe eine Runde, um Wörter zu sammeln.": "Your collection is still empty. Practise a round to collect words.",
  "Deine Session": "Your session",
  "Deine Statistiken": "Your stats",
  "Deine Tasche": "Your bag",
  "Deine Worte": "Your words",
  "Deine Ziele": "Your goals",
  "Deutsches Wort tippen …": "Type the German word …",
  "Die KI prüft deinen Satz": "The AI is checking your sentence",
  "Die Rückmeldung hat nicht geklappt": "The feedback did not come through",
  "Dieser Bereich konnte nicht geladen werden. Dein Lernfortschritt ist gespeichert.": "This area could not be loaded. Your learning progress is saved.",
  "Du bist für heute durch. Komm später wieder für eine neue Runde.": "You are done for today. Come back later for another round.",
  "Du bist hier": "You are here",
  "E-Mail wird bestätigt": "Confirming your email",
  "Einpassen · nochmal für ein zufälliges häufiges Wort": "Fit · tap again for a random common word",
  "Einpassen · nochmal für einen zufälligen Knoten": "Fit · tap again for a random node",
  "Einpassen, erneut tippen für ein zufälliges häufiges Wort": "Fit, tap again for a random common word",
  "Einpassen, erneut tippen für einen zufälligen Knoten": "Fit, tap again for a random node",
  Ergebnis: "Result",
  Erledigt: "Done",
  "Es geht gleich weiter.": "Back in a moment.",
  "Es werden mindestens 4 Redemittel benötigt.": "At least 4 phrases are needed.",
  "Fehlendes Wort": "Missing word",
  Fertig: "Done",
  "Führe dein erstes Gespräch, dann steht hier deine Rückmeldung.": "Have your first conversation and your feedback appears here.",
  "Für diesen Text gibt es keine Korrektur.": "There is no correction for this text.",
  "Für dieses Gespräch gibt es keine Rückmeldung. Dein Gespräch ist trotzdem": "There is no feedback for this conversation. Your conversation is still",
  "Für dieses Thema gibt es keine Aufgaben nach Branche. Du übst hier alle.": "There are no sector-specific tasks for this topic. You practise them all here.",
  "Für dieses Thema gibt es keine Texte nach Branche. Du übst hier alle.": "There are no sector-specific texts for this topic. You practise them all here.",
  "Für dieses Thema gibt es noch keine Einträge.": "There are no entries for this topic yet.",
  "Für dieses Thema gibt es noch keine Übungen.": "There are no exercises for this topic yet.",
  "Für dieses Thema und diese Stufe konnten keine Fragen erzeugt werden.": "No questions could be built for this topic and level.",
  "Gespräch löschen": "Delete conversation",
  "Gespräch verlassen?": "Leave the conversation?",
  "Grüner Punkt = dein Satz.": "Green dot = your sentence.",
  "Hab ich nicht dabei": "I do not have it",
  "Heute ist Prüfungstag": "Today is exam day",
  "Hier ist etwas schiefgelaufen": "Something went wrong here",
  "Hör zu und wähle das fehlende Wort:": "Listen and pick the missing word:",
  "Jetzt üben": "Practise now",
  "KI-Rückmeldung kann Fehler enthalten.": "AI feedback can contain mistakes.",
  "KI-generierte Rückmeldung": "AI-generated feedback",
  Kapitel: "Chapter",
  "Karte umdrehen": "Flip the card",
  "Kein Quiz möglich": "No quiz available",
  "Kein Teil wurde bewertet.": "No part was marked.",
  "Keine Aufgabe für diese Auswahl": "No task for this selection",
  "Keine Kollokationen für dieses Thema.": "No collocations for this topic.",
  "Keine Vokabeln": "No words",
  "Keine Wörter im Graph": "No words in the graph",
  "Keine fälligen Übungen": "No exercises due",
  "Keine Übungen": "No exercises",
  "Komplette Prüfung": "Full exam",
  Lernpfad: "Learning path",
  "Letzte Gespräche": "Recent conversations",
  "Link nicht mehr gültig": "Link no longer valid",
  "Lockere Filter oder Suche, dann erscheinen hier Nomen, Verben und ihre Verbindungen.": "Loosen the filters or the search and nouns, verbs and their links appear here.",
  "Lockere Filter oder Suche, dann erscheinen hier Wörter und ihre Verbindungen.": "Loosen the filters or the search and words and their links appear here.",
  "Löschen": "Delete",
  Min: "min",
  Modus: "Mode",
  "Neue Aufgabe": "New task",
  "Neue Version verfügbar": "New version available",
  "Neuer Satz": "New sentence",
  "Nichts gehört. Versuch es nochmal oder tippe deine Antwort.": "Nothing heard. Try again or type your answer.",
  "Noch kein Ergebnis": "No result yet",
  "Noch keine Auswertungen": "No evaluations yet",
  "Noch keine Dokumente eingepackt.": "No documents packed yet.",
  "Noch keine Ergebnisse": "No results yet",
  "Noch keine Gespräche": "No conversations yet",
  "Noch keine Inhalte": "No content yet",
  "Nochmal hören": "Listen again",
  Notizen: "Notes",
  "Nächste Quest": "Next quest",
  "Nützliche Redemittel": "Useful phrases",
  "Ohne Bewertung": "Without marking",
  "Ohne Bewertung fortfahren": "Continue without marking",
  "Prüf zuerst deinen Satz, dann erkennt die KI Aktiv/Passiv, Zeitform und Modus.": "Check your sentence first, then the AI detects active/passive, tense and mood.",
  "Prüfen": "Check",
  "Prüfung starten": "Start the exam",
  "Reiche deinen ersten Text ein und sieh hier deine Schwachstellen im Verlauf.": "Submit your first text and see your weak spots develop here.",
  "Runde abgeschlossen – stark!": "Round complete, strong work!",
  "Runde geschafft! 🎉": "Round complete! 🎉",
  "Rückmeldung": "Feedback",
  "Satz löschen": "Clear sentence",
  "Schlüssel-Dokument": "Key document",
  "Schreib einen Satz auf Deutsch, zum Beispiel: Der Chef schreibt die E-Mail.": "Write a sentence in German, for example: Der Chef schreibt die E-Mail.",
  "Schreibe hier deinen Text auf Deutsch …": "Write your text in German here …",
  "Schreibe hier deinen Text …": "Write your text here …",
  "Schreiben: dein Text": "Writing: your text",
  "Schwächere Bereiche": "Weaker areas",
  "Setz die Auswahl zurück, dann gibt es wieder etwas zu üben.": "Reset the selection and there will be something to practise again.",
  "Sortiert nach Lernbedarf (oben = meiste Lücken)": "Sorted by what you need most (top = biggest gaps)",
  "Sprich laut – oder tippe deine Antwort.": "Speak out loud, or type your answer.",
  "Starte deine erste Runde, dann siehst du hier deinen Fortschritt.": "Start your first round and your progress shows here.",
  "Strg/Cmd + Scrollen zum Zoomen": "Ctrl/Cmd + scroll to zoom",
  "Stärkeprofil": "Strength profile",
  "Suche nach Nomen, Verb, Übersetzung …": "Search by noun, verb, translation …",
  "Suche nach Thema, Muster …": "Search by topic, pattern …",
  "Suche nach Wendung, Übersetzung …": "Search by phrase, translation …",
  "Tasche schließen": "Close the bag",
  "Tasche öffnen": "Open the bag",
  "Teil abschließen": "Finish this part",
  "Teil abschließen?": "Finish this part?",
  "Text anzeigen": "Show the text",
  "Text der Ansage": "Announcement transcript",
  "Text vergrößern": "Enlarge the text",
  "Textkarte höher oder niedriger ziehen": "Drag the text card taller or shorter",
  "Tipp: In Fokus funktioniert ein Satz am besten.": "Tip: in Fokus one sentence works best.",
  "Tippe auf einen Balken und lerne zuerst, was im Alltag am häufigsten vorkommt.": "Tap a bar and learn what comes up most in daily life first.",
  "Tippe eine andere Form, um ihn umzuwandeln.": "Tap another form to reshape it.",
  "Tippe unten auf die Wörter …": "Tap the words below …",
  "Tippen zum Umdrehen": "Tap to flip",
  "Umlaute einfügen": "Insert umlauts",
  "Verbunden · zum selben Thema": "Related · same topic",
  "Vergrößern": "Zoom in",
  Verkleinern: "Zoom out",
  "Verlauf konnte nicht geladen werden": "History could not be loaded",
  "Vertippt! Der Satz verliert seine Wirkung.": "Typo! The sentence loses its punch.",
  "Vier Teile am Stück, wie am Prüfungstag": "Four parts in one go, like exam day",
  "Was du schon kannst": "What you can already do",
  Weiter: "Next",
  "Weiter bearbeiten": "Keep editing",
  "Weiter sprechen": "Keep speaking",
  "Weiter üben": "Keep practising",
  Wiederholen: "Repeat",
  "Wortschatz nach Häufigkeit": "Vocabulary by frequency",
  "Wähle deine Antwort": "Choose your answer",
  "Wähle deine Schwierigkeitsstufe.": "Choose your difficulty.",
  "Wähle ein Thema mit mindestens 4 Vokabeln für das Quiz.": "Pick a topic with at least 4 words for the quiz.",
  "Wähle einen Bereich": "Choose an area",
  "Wörter, Kollokationen, Redemittel, Grammatik durchsuchen …": "Search words, collocations, phrases, grammar …",
  "Wörterbuch": "Dictionary",
  "Zahl und Kurve": "Number and curve",
  "Zeig das richtige Dokument.": "Show the right document.",
  Zeit: "Time",
  "Zu wenige Vokabeln": "Too few words",
  "Zu wenige Wendungen": "Too few phrases",
  "Zur Übersicht": "To the overview",
  "Zurück nach Neustadt": "Back to Neustadt",
  "du@beispiel.de": "you@example.com",
  "noch kein Durchlauf": "no run yet",
  "noch keine Übung": "no exercise yet",
  "Übe ein Modul, dann siehst du hier deinen Fortschritt.": "Practise a module and your progress shows here.",
  "Üben": "Practise",
  "Überlege zuerst: Wie heißt die Antwort? Dann vergleiche.": "Think first: what is the answer? Then compare.",
  "Übernehmen": "Apply",

  /* --------------------------- labels that reach a sink as German data --- */
  "Module üben": "Practise modules",
  Modelltest: "Mock exam",
  "Ohne Zeit": "Untimed",
  "Mit Zeit": "Timed",
  Lesen: "Reading",
  "Hören": "Listening",
  Schreiben: "Writing",
  Sprechen: "Speaking",
  Verlauf: "History",
  Ansage: "Announcement",
  Ansagen: "announcements",
  Text: "Text",
  Texte: "texts",
  Situationen: "situations",
  "Übung": "exercise",
  "Übungen": "exercises",
  Aufgaben: "tasks",
  "Lesen üben": "Practise reading",
  "Hören üben": "Practise listening",
  "Schreiben üben": "Practise writing",
  "Sprechen üben": "Practise speaking",
  "Zufällige Auswahl": "Random pick",
  "Zufällig": "Random",
  Fokus: "Focus",
  Kurz: "Short",
  Lang: "Long",
  Empfohlen: "Recommended",
  "E-Mail & Nachricht": "Email & message",
  "Beschwerde & Antrag": "Complaint & application",
  "E-Mail (formell)": "Email (formal)",
  "E-Mail (halbformell)": "Email (semi-formal)",
  "E-Mail (privat)": "Email (private)",
  Bewerbung: "Application",
  Beschwerde: "Complaint",
  Bericht: "Report",
  Notiz: "Note",
  Protokoll: "Minutes",
  Stellungnahme: "Opinion piece",
  Forumsbeitrag: "Forum post",
  Widerspruch: "Formal objection",
  Reklamation: "Complaint (goods)",
  "Kündigung": "Termination letter",
  "Übergabe": "Handover",
  Nachricht: "Message",
  Nochmal: "Again",
  Schwer: "Hard",
  Gut: "Good",
  Einfach: "Easy",
  Gemeistert: "Mastered",
  Aktiv: "Active",
  Indikativ: "Indicative",
  "Genus Verbi": "Voice",
  Beispiel: "Example",
  "Präsens": "Present",
  Perfekt: "Present perfect",
  "Futur I": "Future",
  "Konjunktiv II": "Subjunctive II",
  "Can-Dos": "Can-dos",
  Bahnhof: "Station",
  Laden: "Shop",
  Zuhause: "Home",
  Amt: "Public office",
  Trainieren: "Train",
  Spielen: "Play",
  Wendung: "phrase",
  Wendungen: "phrases",
  Kollokation: "collocation",
  Durchlauf: "run",
  "Durchläufe": "runs",
  Antrag: "Application form",
  "Dein Text wird zur Auswertung an eine KI (Anthropic, Google oder OpenAI) gesendet. Die Rückmeldung ist KI-generiert und kann Fehler enthalten.":
    "Your text is sent to an AI (Anthropic, Google or OpenAI) for evaluation. The feedback is AI-generated and can contain mistakes.",
  "Dein Satz wird von einer KI (Anthropic, Google oder OpenAI) geprüft und umgeformt. Die Rückmeldung ist KI-generiert und kann Fehler enthalten.":
    "Your sentence is checked and reshaped by an AI (Anthropic, Google or OpenAI). The feedback is AI-generated and can contain mistakes.",
  "Mehr im Datenschutz.": "More in the privacy policy.",
  "Korrigieren": "Correct it",
  "Zustandspassiv": "Zustandspassiv",
  "Zeitform": "Tense",
  "Grammatik-Ziel": "Grammar target",
  "Aktuelle Serie": "Current streak",
  "Dein Ziel": "Your goal",
  "Diagnose": "Diagnosis",
  "Gesamt-XP": "Total XP",
  "Kompetenz": "Skill",
  "Quest üben": "Practise quest",
  "Session starten": "Start a session",
  "Szenarien": "Scenarios",
  "Vokabeln": "Words",
  "Wörter gemeistert": "words mastered",
  "Ziel": "Target",
  "ohne Punktzahl": "no score",
  "Fortschritt#eyebrow": "Progress",
  "Tagesziel": "Daily goal",
  "Dranbleiben": "Keep going",
};
