import { cn } from "@/lib/utils";

/**
 * The Genauly logo (logo v2 rework, 2026-07-20). Two variants, both tile-less
 * (transparent, no tile) with the Himmel Soft swipe:
 *
 * - "mark" (default): the compact g, for space-constrained spots (mobile
 *   header, favicons keep their own tiled assets). Size with h-* w-* squares.
 * - "wordmark": the full lowercase "genauly" with the swipe under "genau",
 *   the primary logo wherever there is room. Size with h-* w-auto.
 *
 * On dark grounds the artwork is TWO-TONE: whatever sits on the swipe is ink,
 * whatever falls off it is white (only the g's descender, plus "ly" in the
 * wordmark). Both images are rendered and toggled by the `.dark` class (which
 * `useTheme` puts on <html> globally), so the swap is instant and needs no JS.
 * Assets are generated by scripts/branding/build-logo-assets.mjs.
 */
export function Logo({
  className,
  variant = "mark",
}: {
  className?: string;
  variant?: "mark" | "wordmark";
}) {
  const base = variant === "wordmark" ? "/genauly-wordmark" : "/genauly-logo";
  return (
    <>
      <img
        src={`${base}.png`}
        alt="Genauly"
        className={cn("block dark:hidden", className)}
      />
      <img
        src={`${base}-dark.png`}
        alt="Genauly"
        aria-hidden="true"
        className={cn("hidden dark:block", className)}
      />
    </>
  );
}
